# config.yaml example
service:
  name: apache
  container_image: httpd:latest

monitoring:
  name: prometheus
  container_image: prom/prometheus:latest
  container_port: "9090:9090"

motd_message: "Welcome to the server!"
